import { useEffect, useState } from "react";
import {
  getHospitals,
  getMedicines,
  getInventory,
  getPredictions,
} from "../services/api";
import KpiCard from "../components/KpiCard";

export default function Dashboard() {
  const [stats, setStats] = useState({
    hospitals: 0,
    medicines: 0,
    inventory: 0,
    predictions: [],
  });

  useEffect(() => {
    async function loadData() {
      try {
        const [hospitals, medicines, inventory, predictions] =
          await Promise.all([
            getHospitals(),
            getMedicines(),
            getInventory(),
            getPredictions(),
          ]);

        setStats({
          hospitals: hospitals.length,
          medicines: medicines.length,
          inventory: inventory.length,
          predictions,
        });
      } catch (err) {
        console.error("Dashboard Error:", err);
      }
    }

    loadData();
  }, []);

  return (
    <div className="space-y-8">
      {/* AI Recommendation Banner */}

      <div className="rounded-2xl border border-blue-200 bg-blue-50 p-6 flex items-center justify-between">
        <div>
          <p className="text-xs font-bold uppercase tracking-wider text-blue-700">
            AI Recommendation
          </p>

          <h2 className="text-3xl font-bold text-slate-900 mt-2">
            Healthcare Command Center
          </h2>

          <p className="text-gray-600 mt-2">
            Live regional medicine inventory powered by AI prediction.
          </p>
        </div>
      </div>

      {/* KPI Cards */}

      <div className="grid grid-cols-1 gap-6 md:grid-cols-2 xl:grid-cols-4">
        <KpiCard
          title="Connected Hospitals"
          value={stats.hospitals}
          subtitle="Active Network"
          color="blue"
        />

        <KpiCard
          title="Medicines"
          value={stats.medicines}
          subtitle="Available Medicines"
          color="green"
        />

        <KpiCard
          title="Inventory Records"
          value={stats.inventory}
          subtitle="Current Inventory"
          color="amber"
        />

        <KpiCard
          title="AI Predictions"
          value={stats.predictions.length}
          subtitle="Latest Forecasts"
          color="red"
        />
      </div>

      {/* AI Prediction Table */}

      <div className="rounded-2xl border bg-white shadow-sm">
        <div className="border-b p-6">
          <h2 className="text-2xl font-bold">
            Latest AI Predictions
          </h2>

          <p className="text-gray-500 mt-1">
            Live recommendations generated by the AI engine.
          </p>
        </div>

        <div className="overflow-x-auto">
          <table className="w-full">
            <thead className="bg-slate-50">
              <tr className="text-left text-sm text-gray-600">
                <th className="px-6 py-4">Hospital</th>
                <th className="px-6 py-4">Medicine</th>
                <th className="px-6 py-4">Quantity</th>
                <th className="px-6 py-4">Status</th>
                <th className="px-6 py-4">Recommendation</th>
              </tr>
            </thead>

            <tbody>
              {stats.predictions.map((item, index) => (
                <tr
                  key={index}
                  className="border-t hover:bg-slate-50 transition"
                >
                  <td className="px-6 py-4 font-medium">
                    {item.hospital}
                  </td>

                  <td className="px-6 py-4">
                    {item.medicine}
                  </td>

                  <td className="px-6 py-4">
                    {item.quantity}
                  </td>

                  <td className="px-6 py-4">
                    <span
                      className={`rounded-full px-3 py-1 text-xs font-semibold ${
                        item.status === "Healthy"
                          ? "bg-green-100 text-green-700"
                          : item.status === "Overstock"
                          ? "bg-orange-100 text-orange-700"
                          : "bg-red-100 text-red-700"
                      }`}
                    >
                      {item.status}
                    </span>
                  </td>

                  <td className="px-6 py-4 font-medium">
                    {item.recommendation}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>

          {stats.predictions.length === 0 && (
            <div className="p-8 text-center text-gray-500">
              No AI predictions available.
            </div>
          )}
        </div>
      </div>
    </div>
  );
}